spring:
  datasource:
    url: jdbc:mysql://39.108.104.201:25000/xcx?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml